# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Siggers Lab
email: tsiggers@bu.edu
description: Systems biology and gene regulation in the immune system at Boston University.
baseurl: "/siggerslab"
url: "https://shahadat4099.github.io"

include:
  - .htaccess
  - _pages

exclude:
  - team
  - _pages/allnews.md
  - _pages/code.md
  - _pages/data.md
  - code
  - fonts
  - css/academicons
  - js/bootstrap.js
  - js/bootstrap.min.js
  - js/npm.js
  - images/codepic
  - images/contactpic
  - images/logopic
  - images/newspic
  - images/pubpic
  - images/respic
  - images/teampic
  - images/Lab_Logo_v6b.png
  - images/Lab_Logo_v6c.png
  - images/logo1.png
  - images/sanders.png
  - images/siggers/trevor-siggers.png
  - Gemfile.lock

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: false
